language: csharp

solution: Wikibase.Net.sln

mono:
  - latest
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - mono: latest # xunit 2.0.0 fixed on master, see https://github.com/mono/mono/pull/1654

sudo: false

script:
  - xbuild /p:Configuration=Release Wikibase.Net.sln
  - mono ./packages/xunit.runner.console.2.0.0/tools/xunit.console.exe ./Wikibase.Net.Tests/bin/Release/Wikibase.Net.Tests.dll
