language: csharp

solution: Wikibase.Net.sln

sudo: false

install:
  - nuget restore solution-name.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner

script:
  - xbuild /p:Configuration=Release Wikibase.Net.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./Wikibase.Net.Tests/bin/Release/Wikibase.Net.Tests.dll
